export const Theme = {
  ANGLAIS: "ANGLAIS",
  ART: "ART",
  CINEMA: "CINEMA",
  FRANCAIS: "FRANCAIS",
  GEOGRAPHIE: "GEOGRAPHIE",
  HISTOIRE: "HISTOIRE",
  JEUXVIDEO: "JEUXVIDEO",
  LITTERATURE: "LITTERATURE",
  MATHEMATIQUE: "MATHEMATIQUE",
  MUSIQUE: "MUSIQUE",
  SCIENCE: "SCIENCE",
  SPORT: "SPORT",
};
